### ISSUE TITLE
How to enable config.json?

### ISSUE THREAD

**Issue by oshihirii** [dciccale/comment.js#4]
I have this directory structure:

    Desktop
     config.json
     - docs
      - index.html
       - css
       - img
       - js
       code-src.js
       index.html

The contents of `config.json` are:

```
{
  "title": "my documentation title"
}
```

When I run `commentjs config.json` from Desktop directory in terminal, I get:

    No files found for []

Which directory should the `config.json` file be in?  

Which directory should I be in when running `commentjs config.json`?  

Thank You.

**Comment by oshihirii** [comment]
Hmm, I have kept the same directory structure, but changed the contents of `config.json` to:

```
{
  "title": "my documentation title",
  "source": [{
  "path": "/var/www/html/my-site/wsgi/static/js/code.js",
  "link": "https://github.com/user/my-repo/blob/master/wsgi/static/js/code.js"
}],
"output": "docs/index.html"
}
```

And I am getting this error when running `commentjs config.json` from Desktop:

```
/usr/local/lib/node_modules/commentjs/node_modules/minimatch/minimatch.js:138
    throw new TypeError("glob pattern string required")
    ^

TypeError: glob pattern string required
    at new Minimatch (/usr/local/lib/node_modules/commentjs/node_modules/minimatch/minimatch.js:138:11)
    at new Glob (/usr/local/lib/node_modules/commentjs/node_modules/glob/glob.js:157:29)
    at glob (/usr/local/lib/node_modules/commentjs/node_modules/glob/glob.js:57:11)
    at Function.globSync [as sync] (/usr/local/lib/node_modules/commentjs/node_modules/glob/glob.js:76:10)
    at Object.file.expand (/usr/local/lib/node_modules/commentjs/lib/util/file.js:72:20)
    at null.<anonymous> (/usr/local/lib/node_modules/commentjs/lib/scanner.js:87:28)
    at Object._.forEach (/usr/local/lib/node_modules/commentjs/lib/util/util.js:22:16)
    at Scanner.scan (/usr/local/lib/node_modules/commentjs/lib/scanner.js:51:11)
    at Commentjs.run (/usr/local/lib/node_modules/commentjs/lib/comment.js:43:31)
    at Object.<anonymous> (/usr/local/lib/node_modules/commentjs/bin/commentjs:20:22)

```

**Comment by oshihirii** [comment]
This works, but doesn't utilise the link feature:

```
{
"title": "my documentation title",
"source": "/var/www/html/my-site/wsgi/static/js/code.js",
"output": "docs/index.html"
}
```

**Comment by dciccale** [comment]
can you describe better your issue please? what exactly is not working for
you?

**Comment by oshihirii** [comment]
Steps to replicate:

**config.json**

```
{
  "title": "my documentation title",
  "source": [{
  "path": "/var/www/html/my-site/wsgi/static/js/code.js",
  "link": "https://github.com/user/my-repo/blob/master/wsgi/static/js/code.js"
}],
"output": "docs/index.html"
}
```

Then I run:

    me@my-computer:~/Desktop$ commentjs config.json

And it shows this error:

```
/usr/local/lib/node_modules/commentjs/node_modules/minimatch/minimatch.js:138
    throw new TypeError("glob pattern string required")
    ^

TypeError: glob pattern string required
    at new Minimatch (/usr/local/lib/node_modules/commentjs/node_modules/minimatch/minimatch.js:138:11)
    at new Glob (/usr/local/lib/node_modules/commentjs/node_modules/glob/glob.js:157:29)
    at glob (/usr/local/lib/node_modules/commentjs/node_modules/glob/glob.js:57:11)
    at Function.globSync [as sync] (/usr/local/lib/node_modules/commentjs/node_modules/glob/glob.js:76:10)
    at Object.file.expand (/usr/local/lib/node_modules/commentjs/lib/util/file.js:72:20)
    at null.<anonymous> (/usr/local/lib/node_modules/commentjs/lib/scanner.js:87:28)
    at Object._.forEach (/usr/local/lib/node_modules/commentjs/lib/util/util.js:22:16)
    at Scanner.scan (/usr/local/lib/node_modules/commentjs/lib/scanner.js:51:11)
    at Commentjs.run (/usr/local/lib/node_modules/commentjs/lib/comment.js:43:31)
    at Object.<anonymous> (/usr/local/lib/node_modules/commentjs/bin/commentjs:20:22)
```

The process works, however, if I only use this in config.json (but then i can't show a link to github):

```
{
"title": "my documentation title",
"source": "/var/www/html/my-site/wsgi/static/js/code.js",
"output": "docs/index.html"
}
```
I hope that is clear.  

Thank you, I'm really enjoying learning how to use comment.js!  It's really fast and has a great design!

**Comment by dciccale** [comment]
Ok thx, I will take a better look asap
