### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by oshihirii** [dciccale/comment.js#9]
node v6.11.0
comment.js 0.0.6
ubuntu 17.04

**config.json**

```
{
"title": "my documentation",
"source": "/home/me/Music/my_documentation_top_level/MY_CODE.js",
"output": "my_generated_docs/files"
}
```

**generate_docs.sh**

```
#!/bin/sh

# generate documentation
commentjs config.json

# remove previous generated documentation from repository
rm -rf my_documentation/css my_documentation/img my_documentation/js my_documentation/index.html my_documentation/my-src.html 

# move generated files to desired location
mv ~/Music/my_documentation_top_level/my_generated_docs/files/* ~/Music/my_documentation_top_level/my_documentation/

# prepend theme overrides to stylesheet
cat my_docs_theme.css my_documentation/css/docs.css >> temp.css && mv temp.css my_documentation/css/docs.css 
```

Running `./generate_docs.sh ` causes this error:

```
/usr/lib/node_modules/commentjs/lib/tags/definitions.js:105
      types = desc.shift().split(REGEX_TYPES); // desc[2] types
                          ^

TypeError: Cannot read property 'split' of undefined
    at Tag.process (/usr/lib/node_modules/commentjs/lib/tags/definitions.js:105:27)
    at Parser.processBlock (/usr/lib/node_modules/commentjs/lib/parser.js:163:13)
    at Parser.transform (/usr/lib/node_modules/commentjs/lib/parser.js:188:12)
    at Parser.parse (/usr/lib/node_modules/commentjs/lib/parser.js:42:8)
    at Commentjs.run (/usr/lib/node_modules/commentjs/lib/comment.js:54:15)
    at Object.<anonymous> (/usr/lib/node_modules/commentjs/bin/commentjs:20:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

**Comment by oshihirii** [comment]
Hmm, must have been something to do with the content of my comments, i can't pinpoint it exactly, but I just went through all comments and removed the second dash in instances like this:

```
> Parameters

- my_variable (string) - here is a description
```
